export const mockUserData = {
  login: "BrandonArgel",
  id: 66845128,
  node_id: "MDQ6VXNlcjY2ODQ1MTI4",
  avatar_url: "https://avatars.githubusercontent.com/u/66845128?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/BrandonArgel",
  html_url: "https://github.com/BrandonArgel",
  followers_url: "https://api.github.com/users/BrandonArgel/followers",
  following_url: "https://api.github.com/users/BrandonArgel/following{/other_user}",
  gists_url: "https://api.github.com/users/BrandonArgel/gists{/gist_id}",
  starred_url: "https://api.github.com/users/BrandonArgel/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/BrandonArgel/subscriptions",
  organizations_url: "https://api.github.com/users/BrandonArgel/orgs",
  repos_url: "https://api.github.com/users/BrandonArgel/repos",
  events_url: "https://api.github.com/users/BrandonArgel/events{/privacy}",
  received_events_url: "https://api.github.com/users/BrandonArgel/received_events",
  type: "User",
  site_admin: false,
  name: "Brandon Argel Verdeja Dominguez",
  company: null,
  blog: "https://brandonargel.me",
  location: "Zapopan, Jal.",
  email: null,
  hireable: null,
  bio: "Front-End Developer 💻 | Software Engineer 👨‍💻 | Platzi Student 💚",
  twitter_username: "BrandArgel",
  public_repos: 54,
  public_gists: 1,
  followers: 41,
  following: 33,
  created_at: "2020-06-12T18:34:41Z",
  updated_at: "2023-06-15T16:50:27Z"
}