export interface RepositoryModel {
  id: number;
  node_id: string;
  name: string;
  full_name: string;
  private: boolean;
  owner: Owner;
  html_url: string;
  description: null | string;
  fork: boolean;
  url: string;
  forks_url: string;
  keys_url: string;
  collaborators_url: string;
  teams_url: string;
  hooks_url: string;
  issue_events_url: string;
  events_url: string;
  assignees_url: string;
  branches_url: string;
  tags_url: string;
  blobs_url: string;
  git_tags_url: string;
  git_refs_url: string;
  trees_url: string;
  statuses_url: string;
  languages_url: string;
  stargazers_url: string;
  contributors_url: string;
  subscribers_url: string;
  subscription_url: string;
  commits_url: string;
  git_commits_url: string;
  comments_url: string;
  issue_comment_url: string;
  contents_url: string;
  compare_url: string;
  merges_url: string;
  archive_url: string;
  downloads_url: string;
  issues_url: string;
  pulls_url: string;
  milestones_url: string;
  notifications_url: string;
  labels_url: string;
  releases_url: string;
  deployments_url: string;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  pushed_at?: string | null | undefined;
  git_url?: string | undefined;
  ssh_url?: string | undefined;
  clone_url?: string | undefined;
  svn_url?: string | undefined;
  homepage?: string | null | undefined;
  size?: number | undefined;
  stargazers_count?: number | undefined;
  watchers_count?: number | undefined;
  language?: string | null | undefined;
  has_issues?: boolean | undefined;
  has_projects?: boolean | undefined;
  has_downloads?: boolean | undefined;
  has_wiki?: boolean | undefined;
  has_pages?: boolean | undefined;
  has_discussions?: boolean | undefined;
  forks_count?: number | undefined;
  mirror_url?: string | null | undefined;
  archived?: boolean | undefined;
  disabled?: boolean | undefined;
  open_issues_count?: number | undefined;
  license?: License | null | undefined;
  allow_forking?: boolean | undefined;
  is_template?: boolean | undefined;
  web_commit_signoff_required?: boolean | undefined;
  topics?: string[] | undefined;
  visibility?: string | undefined;
  forks?: number | undefined;
  open_issues?: number | undefined;
  watchers?: number | undefined;
  default_branch?: string | undefined;
}

export interface License { 
  key?: string | undefined; 
  name?: string | undefined; 
  spdx_id?: string | undefined; 
  url?: string | undefined; 
  node_id?: string | undefined;
}


export interface Owner {
  login: string | null;
  id: number | null;
  node_id: string | null;
  avatar_url: string | null;
  gravatar_id: string | null;
  url: string | null;
  html_url: string | null;
  followers_url: string | null;
  following_url: string | null;
  gists_url: string | null;
  starred_url: string | null;
  subscriptions_url: string | null;
  organizations_url: string | null;
  repos_url: string | null;
  events_url: string | null;
  received_events_url: string | null;
  type: string | null;
  site_admin: boolean | null;
}
